apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: registry.redhat.io/rhel8/postgresql-15
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRESQL_USER
              value: testuser
            - name: POSTGRESQL_PASSWORD
              value: testpassword
            - name: POSTGRESQL_DATABASE
              value: keycloak
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: pgdata
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-db
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql