apiVersion: v1
kind: ConfigMap
metadata:
  name: datagrid-rhbk-config
  namespace: datagrid
data:
  infinispan-config.xml: |
    <infinispan
        xmlns="urn:infinispan:config:15.0"
        xmlns:server="urn:infinispan:server:15.0">

      <cache-container name="default">
        <security>
          <authorization group-only-mapping="true">
            <identity-role-mapper/>
          </authorization>
        </security>
      </cache-container>

      <server xmlns="urn:infinispan:server:15.0">
        <security>
          <security-realms>

            <security-realm name="default">
              <server-identities>
                <ssl>
                  <keystore
                      path="/etc/security/conf/operator-security/keystore.pem"
                      password=""/>
                </ssl>
              </server-identities>

              <token-realm
                  name="datagrid"
                  principal-claim="preferred_username"
                  auth-server-url="<URL_KEYCLOAK>:443"
                  client-id="datagrid-console">

                <oauth2-introspection
                    introspection-url="<URL_KEYCLOAK>:443/realms/<NOME_REALM>/protocol/openid-connect/token/introspect"
                    client-id="datagrid-server"
                    client-ssl-context="default"
                    host-name-verification-policy="DEFAULT">
                    
                    <credential-reference
                        store="credentials"
                        alias="client-secret"/>

                </oauth2-introspection>

              </token-realm>

            </security-realm>

          </security-realms>
        </security>

        <endpoints>
          <endpoint
              socket-binding="default"
              security-realm="default"/>
        </endpoints>

      </server>
    </infinispan>
