apiVersion: infinispan.org/v1
kind: Infinispan

metadata:
  name: infinispan
  namespace: datagrid

spec:
  replicas: 2

  service:
    type: DataGrid

  expose:
    type: Route

  configMapName: datagrid-rhbk-config

  security:
    authorization:
      enabled: true

    credentialStoreSecretName: datagrid-rhbk-secret